import type { AdminResourceConfig } from "./admin-crud.types.js";

export const adminResourceConfigs: Record<string, AdminResourceConfig> = {
  "khoa": {
    resource: "khoa",
    modelKey: "khoa",
    idField: "khoaId",
    searchFields: ["maKhoa", "tenKhoa"],
    defaultOrderBy: { khoaId: "desc" },
  },
  "bo-mon": {
    resource: "bo-mon",
    modelKey: "boMon",
    idField: "boMonId",
    searchFields: ["maBoMon", "tenBoMon"],
    defaultOrderBy: { boMonId: "desc" },
    include: { khoa: true },
  },
  "nganh": {
    resource: "nganh",
    modelKey: "nganh",
    idField: "nganhId",
    searchFields: ["maNganh", "tenNganh"],
    defaultOrderBy: { nganhId: "desc" },
    include: { khoa: true },
  },
  "chuyen-nganh": {
    resource: "chuyen-nganh",
    modelKey: "chuyenNganh",
    idField: "chuyenNganhId",
    searchFields: ["maChuyenNganh", "tenChuyenNganh"],
    defaultOrderBy: { chuyenNganhId: "desc" },
    include: { nganh: true },
  },
  "co-so": {
    resource: "co-so",
    modelKey: "coSo",
    idField: "coSoId",
    searchFields: ["maCoSo", "tenCoSo", "diaChi"],
    defaultOrderBy: { coSoId: "desc" },
  },
  "phong-hoc": {
    resource: "phong-hoc",
    modelKey: "phongHoc",
    idField: "phongHocId",
    searchFields: ["maPhong", "tenPhong", "loaiPhong"],
    defaultOrderBy: { phongHocId: "desc" },
    include: { coSo: true },
  },
  "khoa-hoc": {
    resource: "khoa-hoc",
    modelKey: "khoaHoc",
    idField: "khoaHocId",
    searchFields: ["maKhoaHoc", "tenKhoaHoc"],
    defaultOrderBy: { khoaHocId: "desc" },
  },
  "lop": {
    resource: "lop",
    modelKey: "lop",
    idField: "lopId",
    searchFields: ["maLop", "tenLop", "heDaoTao"],
    defaultOrderBy: { lopId: "desc" },
    include: { khoaHoc: true, nganh: true, chuyenNganh: true, coSo: true },
  },
  "giang-vien": {
    resource: "giang-vien",
    modelKey: "giangVien",
    idField: "giangVienId",
    searchFields: ["maGiangVien", "hoTen", "email", "soDienThoai", "hocVi", "chucDanh"],
    defaultOrderBy: { giangVienId: "desc" },
    include: { boMon: true },
  },
  "hoc-phan": {
    resource: "hoc-phan",
    modelKey: "hocPhan",
    idField: "hocPhanId",
    searchFields: ["maHocPhan", "tenHocPhan", "loaiHocPhan"],
    defaultOrderBy: { hocPhanId: "desc" },
  },
  "giang-vien-hoc-phan": {
    resource: "giang-vien-hoc-phan",
    modelKey: "giangVienHocPhan",
    idField: "giangVienHocPhanId",
    searchFields: ["ghiChu"],
    defaultOrderBy: { giangVienHocPhanId: "desc" },
    include: { giangVien: true, hocPhan: true },
  },
  "nam-hoc": {
    resource: "nam-hoc",
    modelKey: "namHoc",
    idField: "namHocId",
    searchFields: ["maNamHoc", "trangThai"],
    defaultOrderBy: { namHocId: "desc" },
  },
  "hoc-ky": {
    resource: "hoc-ky",
    modelKey: "hocKy",
    idField: "hocKyId",
    searchFields: ["maHocKy", "tenHocKy", "trangThai"],
    defaultOrderBy: { hocKyId: "desc" },
    include: { namHoc: true },
  },
  "chuong-trinh-dao-tao": {
    resource: "chuong-trinh-dao-tao",
    modelKey: "chuongTrinhDaoTao",
    idField: "chuongTrinhId",
    searchFields: ["maChuongTrinh", "tenChuongTrinh", "trinhDoDaoTao", "hinhThucDaoTao"],
    defaultOrderBy: { chuongTrinhId: "desc" },
    include: { nganh: true, chuyenNganh: true, khoaHoc: true },
  },
  "chuong-trinh-hoc-phan": {
    resource: "chuong-trinh-hoc-phan",
    modelKey: "chuongTrinhHocPhan",
    idField: "chuongTrinhHocPhanId",
    searchFields: ["tienDo", "ghiChu"],
    defaultOrderBy: { chuongTrinhHocPhanId: "desc" },
    include: { chuongTrinhDaoTao: true, hocPhan: true },
  },
  "lop-chuong-trinh": {
    resource: "lop-chuong-trinh",
    modelKey: "lopChuongTrinh",
    idField: "lopChuongTrinhId",
    searchFields: ["trangThai", "ghiChu"],
    defaultOrderBy: { lopChuongTrinhId: "desc" },
    include: { lop: true, chuongTrinhDaoTao: true },
  },
  "tien-do-hoc-phan-lop": {
    resource: "tien-do-hoc-phan-lop",
    modelKey: "tienDoHocPhanLop",
    idField: "tienDoId",
    searchFields: ["tienDoDuKien", "trangThai", "ghiChu"],
    defaultOrderBy: { tienDoId: "desc" },
    include: { lop: true, chuongTrinhHocPhan: { include: { hocPhan: true } } },
  },
  "ke-hoach-dao-tao": {
    resource: "ke-hoach-dao-tao",
    modelKey: "keHoachDaoTao",
    idField: "keHoachId",
    searchFields: ["maKeHoach", "tenKeHoach", "trangThai"],
    defaultOrderBy: { keHoachId: "desc" },
    include: { namHoc: true, khoa: true },
  },
  "ke-hoach-hoc-ky": {
    resource: "ke-hoach-hoc-ky",
    modelKey: "keHoachHocKy",
    idField: "keHoachHocKyId",
    searchFields: ["tenKeHoachHocKy", "trangThai"],
    defaultOrderBy: { keHoachHocKyId: "desc" },
    include: { keHoachDaoTao: true, hocKy: true },
  },
  "tuan-dao-tao": {
    resource: "tuan-dao-tao",
    modelKey: "tuanDaoTao",
    idField: "tuanId",
    searchFields: ["tenTuan", "loaiTuan", "ghiChu"],
    defaultOrderBy: { soTuan: "asc" },
    include: { keHoachDaoTao: true },
  },
  "ke-hoach-lop-hoc-phan": {
    resource: "ke-hoach-lop-hoc-phan",
    modelKey: "keHoachLopHocPhan",
    idField: "keHoachLopHocPhanId",
    searchFields: ["tienDo", "trangThai", "lyDoThem"],
    defaultOrderBy: { keHoachLopHocPhanId: "desc" },
    include: { keHoachHocKy: true, lop: true, hocPhan: true, chuongTrinhHocPhan: true },
  },
  "nhom-hoc-phan": {
    resource: "nhom-hoc-phan",
    modelKey: "nhomHocPhan",
    idField: "nhomHocPhanId",
    searchFields: ["maNhom", "tenNhom", "loaiNhom"],
    defaultOrderBy: { nhomHocPhanId: "desc" },
    include: { keHoachLopHocPhan: { include: { lop: true, hocPhan: true } } },
  },
  "phan-cong-giang-day": {
    resource: "phan-cong-giang-day",
    modelKey: "phanCongGiangDay",
    idField: "phanCongId",
    searchFields: ["vaiTro", "trangThai", "ghiChu"],
    defaultOrderBy: { phanCongId: "desc" },
    include: { giangVien: true, nhomHocPhan: { include: { keHoachLopHocPhan: { include: { lop: true, hocPhan: true } } } } },
  },
  "lich-day-theo-tuan": {
    resource: "lich-day-theo-tuan",
    modelKey: "lichDayTheoTuan",
    idField: "lichTuanId",
    searchFields: ["noiDungGiangDay", "ghiChu"],
    defaultOrderBy: { lichTuanId: "desc" },
    include: { phanCongGiangDay: true, tuanDaoTao: true, phongHoc: true },
  },
};

export const getAdminResourceConfig = (resource: string) => adminResourceConfigs[resource];
