import {
  BookOpen,
  Building2,
  GraduationCap,
  Layers3,
  School,
  Users,
} from "lucide-react";
import type { AdminCrudConfig } from "./adminCrud.types";

const subjectTypes = [
  { label: "Dai cuong", value: "dai_cuong" },
  { label: "Co so nganh", value: "co_so_nganh" },
  { label: "Chuyen nganh", value: "chuyen_nganh" },
  { label: "Do an", value: "do_an" },
  { label: "Thuc tap", value: "thuc_tap" },
  { label: "Tot nghiep", value: "tot_nghiep" },
  { label: "Khac", value: "khac" },
];

export const adminCrudConfigs: Record<string, AdminCrudConfig> = {
  khoa: {
    resource: "khoa",
    path: "khoa",
    title: "Khoa",
    description: "Quan ly ma khoa, ten khoa va du lieu nen cho bo mon, nganh.",
    primaryAction: "Them khoa",
    icon: School,
    idField: "khoaId",
    searchPlaceholder: "Tim theo ma khoa, ten khoa...",
    fields: [
      { name: "maKhoa", label: "Ma khoa", type: "text", required: true },
      { name: "tenKhoa", label: "Ten khoa", type: "text", required: true },
    ],
    columns: [
      { key: "maKhoa", label: "Ma khoa" },
      { key: "tenKhoa", label: "Ten khoa" },
      { key: "ngayTao", label: "Ngay tao" },
    ],
  },
  bomon: {
    resource: "bomon",
    path: "bomon",
    title: "Bo mon",
    description: "Quan ly bo mon truc thuoc khoa va dung lam don vi cua giang vien.",
    primaryAction: "Them bo mon",
    icon: Building2,
    idField: "boMonId",
    searchPlaceholder: "Tim theo ma bo mon, ten bo mon...",
    fields: [
      { name: "khoaId", label: "Khoa ID", type: "number", required: true, min: 1 },
      { name: "maBoMon", label: "Ma bo mon", type: "text", required: true },
      { name: "tenBoMon", label: "Ten bo mon", type: "text", required: true },
    ],
    columns: [
      { key: "maBoMon", label: "Ma bo mon" },
      { key: "tenBoMon", label: "Ten bo mon" },
      { key: "khoa.tenKhoa", label: "Khoa" },
    ],
  },
  nganh: {
    resource: "nganh",
    path: "nganh",
    title: "Nganh",
    description: "Quan ly nganh dao tao theo khoa.",
    primaryAction: "Them nganh",
    icon: GraduationCap,
    idField: "nganhId",
    searchPlaceholder: "Tim theo ma nganh, ten nganh...",
    fields: [
      { name: "khoaId", label: "Khoa ID", type: "number", required: true, min: 1 },
      { name: "maNganh", label: "Ma nganh", type: "text", required: true },
      { name: "tenNganh", label: "Ten nganh", type: "text", required: true },
    ],
    columns: [
      { key: "maNganh", label: "Ma nganh" },
      { key: "tenNganh", label: "Ten nganh" },
      { key: "khoa.tenKhoa", label: "Khoa" },
    ],
  },
  chuyennganh: {
    resource: "chuyennganh",
    path: "chuyennganh",
    title: "Chuyen nganh",
    description: "Quan ly chuyen nganh truc thuoc nganh dao tao.",
    primaryAction: "Them chuyen nganh",
    icon: Layers3,
    idField: "chuyenNganhId",
    searchPlaceholder: "Tim theo ma chuyen nganh, ten chuyen nganh...",
    fields: [
      { name: "nganhId", label: "Nganh ID", type: "number", required: true, min: 1 },
      { name: "maChuyenNganh", label: "Ma chuyen nganh", type: "text" },
      { name: "tenChuyenNganh", label: "Ten chuyen nganh", type: "text", required: true },
    ],
    columns: [
      { key: "maChuyenNganh", label: "Ma chuyen nganh", fallback: "-" },
      { key: "tenChuyenNganh", label: "Ten chuyen nganh" },
      { key: "nganh.tenNganh", label: "Nganh" },
    ],
  },
  giangvien: {
    resource: "giangvien",
    path: "giangvien",
    title: "Giang vien",
    description: "Quan ly ho so giang vien, bo mon, dinh muc gio va trang thai.",
    primaryAction: "Them giang vien",
    icon: Users,
    idField: "giangVienId",
    searchPlaceholder: "Tim theo ma, ho ten, email, bo mon...",
    fields: [
      { name: "boMonId", label: "Bo mon ID", type: "number", min: 1 },
      { name: "maGiangVien", label: "Ma giang vien", type: "text" },
      { name: "hoTen", label: "Ho ten", type: "text", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "soDienThoai", label: "So dien thoai", type: "text" },
      { name: "hocVi", label: "Hoc vi", type: "text" },
      { name: "chucDanh", label: "Chuc danh", type: "text" },
      { name: "dinhMucGio", label: "Dinh muc gio", type: "number", min: 0 },
      {
        name: "trangThai",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Dang giang day", value: "dang_giang_day" },
          { label: "Tam nghi", value: "tam_nghi" },
        ],
      },
    ],
    columns: [
      { key: "maGiangVien", label: "Ma GV", fallback: "-" },
      { key: "hoTen", label: "Ho ten" },
      { key: "boMon.tenBoMon", label: "Bo mon", fallback: "-" },
      { key: "trangThai", label: "Trang thai" },
    ],
  },
  lop: {
    resource: "lop",
    path: "lop",
    title: "Lop",
    description: "Quan ly lop, khoa hoc, nganh, chuyen nganh, si so va trang thai.",
    primaryAction: "Them lop",
    icon: Layers3,
    idField: "lopId",
    searchPlaceholder: "Tim theo ma lop, ten lop, he dao tao...",
    fields: [
      { name: "maLop", label: "Ma lop", type: "text", required: true },
      { name: "tenLop", label: "Ten lop", type: "text", required: true },
      { name: "khoaHocId", label: "Khoa hoc ID", type: "number", required: true, min: 1 },
      { name: "nganhId", label: "Nganh ID", type: "number", required: true, min: 1 },
      { name: "chuyenNganhId", label: "Chuyen nganh ID", type: "number", min: 1 },
      { name: "coSoId", label: "Co so ID", type: "number", min: 1 },
      { name: "heDaoTao", label: "He dao tao", type: "text" },
      { name: "siSo", label: "Si so", type: "number", min: 0 },
      { name: "thoiGianNhapHoc", label: "Ngay nhap hoc", type: "date" },
      { name: "thoiGianTotNghiep", label: "Ngay tot nghiep", type: "date" },
      {
        name: "trangThai",
        label: "Trang thai",
        type: "select",
        options: [
          { label: "Dang hoc", value: "dang_hoc" },
          { label: "Da tot nghiep", value: "da_tot_nghiep" },
          { label: "Tam ngung", value: "tam_ngung" },
        ],
      },
      { name: "ghiChu", label: "Ghi chu", type: "textarea" },
    ],
    columns: [
      { key: "maLop", label: "Ma lop" },
      { key: "tenLop", label: "Ten lop" },
      { key: "nganh.tenNganh", label: "Nganh" },
      { key: "siSo", label: "Si so", fallback: "0" },
      { key: "trangThai", label: "Trang thai" },
    ],
  },
  hocphan: {
    resource: "hocphan",
    path: "hocphan",
    title: "Hoc phan",
    description: "Quan ly ma hoc phan, tin chi, tiet ly thuyet, thuc hanh va bo mon.",
    primaryAction: "Them hoc phan",
    icon: BookOpen,
    idField: "hocPhanId",
    searchPlaceholder: "Tim theo ma hoc phan, ten hoc phan...",
    fields: [
      { name: "maHocPhan", label: "Ma hoc phan", type: "text", required: true },
      { name: "tenHocPhan", label: "Ten hoc phan", type: "text", required: true },
      { name: "soTinChi", label: "So tin chi", type: "number", required: true, min: 0 },
      { name: "soTietLyThuyet", label: "Tiet ly thuyet", type: "number", required: true, min: 0 },
      { name: "soTietThucHanh", label: "Tiet thuc hanh", type: "number", required: true, min: 0 },
      { name: "tongSoTiet", label: "Tong so tiet", type: "number", min: 0 },
      { name: "boMonId", label: "Bo mon ID", type: "number", min: 1 },
      { name: "loaiHocPhan", label: "Loai hoc phan", type: "select", options: subjectTypes },
      { name: "moTa", label: "Mo ta", type: "textarea" },
    ],
    columns: [
      { key: "maHocPhan", label: "Ma HP" },
      { key: "tenHocPhan", label: "Ten hoc phan" },
      { key: "soTinChi", label: "Tin chi" },
      { key: "tongSoTiet", label: "Tong tiet" },
      { key: "boMon.tenBoMon", label: "Bo mon", fallback: "-" },
    ],
  },
};

export const adminCrudConfigList = Object.values(adminCrudConfigs);
